# Pytis translations 
# Copyright (C) 2008-2011 Brailcom, o.p.s. 
# This file is distributed under the same license as the Pytis package. 
#
msgid ""
msgstr ""
"Project-Id-Version: 0.1\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-07-28 20:58+0200\n"
"PO-Revision-Date: 2011-12-29 14:56+0100\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: Hungarian <wiking@lists.freebsoft.org>\n"
"Language: hu\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: ../lib/pytis/data/access.py:434
msgid "Access denied"
msgstr ""

#: ../lib/pytis/data/dbapi.py:78
msgid "Waiting for server recovery"
msgstr ""

#: ../lib/pytis/data/dbapi.py:90
msgid "Can't connect to database"
msgstr ""

#: ../lib/pytis/data/dbapi.py:209
msgid "Database interface error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:228
msgid "Database connection timeout"
msgstr ""

#: ../lib/pytis/data/dbapi.py:230 ../lib/pytis/data/dbapi.py:341
msgid "Database connection error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:244
msgid "Database operational error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:248
msgid "Database integrity violation"
msgstr ""

#: ../lib/pytis/data/dbdata.py:299
msgid "Too many database connections"
msgstr ""

#: ../lib/pytis/data/dbdata.py:707
msgid "Database error"
msgstr ""

#: ../lib/pytis/data/dbdata.py:775
msgid "Invalid user name or password"
msgstr ""

#: ../lib/pytis/data/postgresql.py:457 ../lib/pytis/data/postgresql.py:541
#: ../lib/pytis/data/postgresql.py:553
msgid "Method not implemented"
msgstr ""

#: ../lib/pytis/data/postgresql.py:2064
msgid "Application error. You can report it to get it fixed soon."
msgstr ""

#: ../lib/pytis/data/postgresql.py:3804
msgid "Invalid database counter value"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:162
msgid "Empty value"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:164
msgid "Invalid value"
msgstr ""

#: ../lib/pytis/data/types_.py:399
#, python-format
msgid "Wildcard matching not supported for values of type '%s'."
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:543
#, python-format
msgid "Minimal value is %(minimum)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:546
#, python-format
msgid "Maximal value is %(maximum)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:623
#, python-format
msgid "Minimal size %(minlen)s not satisfied"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:626
#, python-format
msgid "Maximal length %(maxlen)s characters exceeded"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:737
msgid "Not an integer"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:861
msgid "Invalid number"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1047
#, python-format
msgid "Minimal length %(minlen)s characters not satisfied"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1049 ../lib/pytis/data/types_.py:2220
#, python-format
msgid "Maximal size %(maxlen)s exceeded"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1151
msgid "Enter the password twice to eliminate typos"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1154
msgid "Passwords don't match"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1157
msgid "Invalid MD5 hash"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1160
msgid "Please use mix of letters and non-letters in your password"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1222 ../lib/pytis/data/types_.py:1258
#: ../lib/pytis/data/types_.py:1294 ../lib/pytis/data/types_.py:1314
#: ../lib/pytis/data/types_.py:2021
msgid "Invalid format"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1244
msgid "Invalid color format ('#RGB' or '#RRGGBB')"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1260
#, python-format
msgid "Invalid inet address mask: %(mask)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1262
#, python-format
msgid "Invalid inet address value %(addr)s"
msgstr ""

#: ../lib/pytis/data/types_.py:1448
msgid "Invalid date or time format"
msgstr ""

#: ../lib/pytis/data/types_.py:1449
msgid "Invalid date or time"
msgstr ""

#: ../lib/pytis/data/types_.py:1450
msgid "Date outside the allowed range"
msgstr ""

#: ../lib/pytis/data/types_.py:2180
msgid "Invalid boolean type input value"
msgstr ""

#: ../lib/pytis/data/types_.py:2266
#, python-format
msgid "Not a buffer object: %r"
msgstr ""

#: ../lib/pytis/data/types_.py:2407
#, python-format
msgid "Maximal pixel size %(maxsize)s exceeded"
msgstr ""

#: ../lib/pytis/data/types_.py:2409
#, python-format
msgid "Minimal pixel size %(minsize)s exceeded"
msgstr ""

#: ../lib/pytis/data/types_.py:2411
#, python-format
msgid "Unsupported format %(format)s; valid formats: %(formats)s"
msgstr ""

#: ../lib/pytis/data/types_.py:2427
msgid "Invalid graphics format"
msgstr ""

#: ../lib/pytis/data/types_.py:2532
msgid "Invalid hierarchical value format"
msgstr ""

#: ../lib/pytis/data/types_.py:2534
msgid "One of hierarchical value items is too long"
msgstr ""

#: ../lib/pytis/data/types_.py:2536
msgid "One of hierarchical value items contains invalid characters"
msgstr ""

#, fuzzy
#~ msgid "Instructions"
#~ msgstr "Műveletek"

#, fuzzy
#~ msgid "Selections"
#~ msgstr "Műveletek"

#, fuzzy
#~ msgid "Dictation"
#~ msgstr "Műveletek"
