# Pytis translations 
# Copyright (C) 2008-2011 Brailcom, o.p.s. 
# This file is distributed under the same license as the Pytis package. 
#
msgid ""
msgstr ""
"Project-Id-Version: 0.1\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-08-26 13:41+0200\n"
"PO-Revision-Date: 2011-12-29 14:56+0100\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: Hungarian <wiking@lists.freebsoft.org>\n"
"Language: hu\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: ../lib/pytis/data/access.py:434
msgid "Access denied"
msgstr ""

#: ../lib/pytis/data/dbapi.py:78
msgid "Waiting for server recovery"
msgstr ""

#: ../lib/pytis/data/dbapi.py:90
msgid "Can't connect to database"
msgstr ""

#: ../lib/pytis/data/dbapi.py:212
msgid "Database interface error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:231
msgid "Database connection timeout"
msgstr ""

#: ../lib/pytis/data/dbapi.py:233 ../lib/pytis/data/dbapi.py:345
msgid "Database connection error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:247
msgid "Database operational error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:251
msgid "Database integrity violation"
msgstr ""

#: ../lib/pytis/data/dbdata.py:299
msgid "Too many database connections"
msgstr ""

#: ../lib/pytis/data/dbdata.py:707
msgid "Database error"
msgstr ""

#: ../lib/pytis/data/dbdata.py:775
msgid "Invalid user name or password"
msgstr ""

#: ../lib/pytis/data/postgresql.py:457 ../lib/pytis/data/postgresql.py:541
#: ../lib/pytis/data/postgresql.py:553
msgid "Method not implemented"
msgstr ""

#: ../lib/pytis/data/postgresql.py:2067
msgid "Application error. You can report it to get it fixed soon."
msgstr ""

#: ../lib/pytis/data/postgresql.py:3807
msgid "Invalid database counter value"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:162
msgid "Empty value"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:164
msgid "Invalid value"
msgstr ""

#: ../lib/pytis/data/types_.py:395
#, python-format
msgid "Wildcard matching not supported for values of type '%s'."
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:539
#, python-format
msgid "Minimal value is %(minimum)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:542
#, python-format
msgid "Maximal value is %(maximum)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:619
#, python-format
msgid "Minimal size %(minlen)s not satisfied"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:622
#, python-format
msgid "Maximal length %(maxlen)s characters exceeded"
msgstr ""

#: ../lib/pytis/data/types_.py:684
msgid "Lower range bound higher than the upper one"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:868
msgid "Not an integer"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1008
msgid "Invalid number"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1194
#, python-format
msgid "Minimal length %(minlen)s characters not satisfied"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1196 ../lib/pytis/data/types_.py:2375
#, python-format
msgid "Maximal size %(maxlen)s exceeded"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1298
msgid "Enter the password twice to eliminate typos"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1301
msgid "Passwords don't match"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1304
msgid "Invalid MD5 hash"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1307
msgid "Please use mix of letters and non-letters in your password"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1369 ../lib/pytis/data/types_.py:1405
#: ../lib/pytis/data/types_.py:1441 ../lib/pytis/data/types_.py:1461
#: ../lib/pytis/data/types_.py:2176
msgid "Invalid format"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1391
msgid "Invalid color format ('#RGB' or '#RRGGBB')"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1407
#, python-format
msgid "Invalid inet address mask: %(mask)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1409
#, python-format
msgid "Invalid inet address value %(addr)s"
msgstr ""

#: ../lib/pytis/data/types_.py:1595
msgid "Invalid date or time format"
msgstr ""

#: ../lib/pytis/data/types_.py:1596
msgid "Invalid date or time"
msgstr ""

#: ../lib/pytis/data/types_.py:1597
msgid "Date outside the allowed range"
msgstr ""

#: ../lib/pytis/data/types_.py:2335
msgid "Invalid boolean type input value"
msgstr ""

#: ../lib/pytis/data/types_.py:2421
#, python-format
msgid "Not a buffer object: %r"
msgstr ""

#: ../lib/pytis/data/types_.py:2562
#, python-format
msgid "Maximal pixel size %(maxsize)s exceeded"
msgstr ""

#: ../lib/pytis/data/types_.py:2564
#, python-format
msgid "Minimal pixel size %(minsize)s exceeded"
msgstr ""

#: ../lib/pytis/data/types_.py:2566
#, python-format
msgid "Unsupported format %(format)s; valid formats: %(formats)s"
msgstr ""

#: ../lib/pytis/data/types_.py:2582
msgid "Invalid graphics format"
msgstr ""

#: ../lib/pytis/data/types_.py:2687
msgid "Invalid hierarchical value format"
msgstr ""

#: ../lib/pytis/data/types_.py:2689
msgid "One of hierarchical value items is too long"
msgstr ""

#: ../lib/pytis/data/types_.py:2691
msgid "One of hierarchical value items contains invalid characters"
msgstr ""

#, fuzzy
#~ msgid "Instructions"
#~ msgstr "Műveletek"

#, fuzzy
#~ msgid "Selections"
#~ msgstr "Műveletek"

#, fuzzy
#~ msgid "Dictation"
#~ msgstr "Műveletek"
