# Pytis translations 
# Copyright (C) 2008-2011 OUI Technology Ltd. 
# This file is distributed under the same license as the Pytis package. 
#
msgid ""
msgstr ""
"Project-Id-Version: 0.1\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2019-01-10 12:38+0100\n"
"PO-Revision-Date: 2011-12-29 14:56+0100\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: Hungarian <wiking@lists.freebsoft.org>\n"
"Language: hu\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: ../lib/pytis/data/access.py:431
msgid "Access denied"
msgstr ""

#: ../lib/pytis/data/dbapi.py:81
msgid "Waiting for server recovery"
msgstr ""

#: ../lib/pytis/data/dbapi.py:93
msgid "Can't connect to database"
msgstr ""

#: ../lib/pytis/data/dbapi.py:218
msgid "Database interface error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:237
msgid "Database connection timeout"
msgstr ""

#: ../lib/pytis/data/dbapi.py:239 ../lib/pytis/data/dbapi.py:373
msgid "Database connection error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:253
msgid "Database operational error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:260
msgid "Database internal error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:264
msgid "Database integrity violation"
msgstr ""

#: ../lib/pytis/data/dbdata.py:302
msgid "Too many database connections"
msgstr ""

#: ../lib/pytis/data/dbdata.py:711
msgid "Database error"
msgstr ""

#: ../lib/pytis/data/dbdata.py:779
msgid "Invalid user name or password"
msgstr ""

#: ../lib/pytis/data/postgresql.py:463 ../lib/pytis/data/postgresql.py:559
#: ../lib/pytis/data/postgresql.py:571
msgid "Method not implemented"
msgstr ""

#: ../lib/pytis/data/postgresql.py:3911
msgid "Invalid database counter value"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:162
msgid "Empty value"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:164
msgid "Invalid value"
msgstr ""

#: ../lib/pytis/data/types_.py:398
#, python-format
msgid "Wildcard matching not supported for values of type '%s'."
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:569
#, python-format
msgid "Minimal value is %(minimum)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:572
#, python-format
msgid "Maximal value is %(maximum)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:651
#, python-format
msgid "Minimal size %(minlen)s not satisfied"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:654
#, python-format
msgid "Maximal length %(maxlen)s characters exceeded"
msgstr ""

#: ../lib/pytis/data/types_.py:716
msgid "Lower range bound higher than the upper one"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:902
msgid "Not an integer"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1054
msgid "Invalid number"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1240
#, python-format
msgid "Minimal length %(minlen)s characters not satisfied"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1242 ../lib/pytis/data/types_.py:2437
#, python-format
msgid "Maximal size %(maxlen)s exceeded"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1344
msgid "Enter the password twice to eliminate typos"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1347
msgid "Passwords don't match"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1350
msgid "Invalid MD5 hash"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1353
msgid "Please use mix of letters and non-letters in your password"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1415 ../lib/pytis/data/types_.py:1449
#: ../lib/pytis/data/types_.py:1485 ../lib/pytis/data/types_.py:1505
#: ../lib/pytis/data/types_.py:2236
msgid "Invalid format"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1435
msgid "Invalid color format ('#RGB' or '#RRGGBB')"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1451
#, python-format
msgid "Invalid inet address mask: %(mask)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1453
#, python-format
msgid "Invalid inet address value %(addr)s"
msgstr ""

#: ../lib/pytis/data/types_.py:1641
msgid "Invalid date or time format"
msgstr ""

#: ../lib/pytis/data/types_.py:1642
msgid "Invalid date or time"
msgstr ""

#: ../lib/pytis/data/types_.py:1643
msgid "Date outside the allowed range"
msgstr ""

#: ../lib/pytis/data/types_.py:2397
msgid "Invalid boolean type input value"
msgstr ""

#: ../lib/pytis/data/types_.py:2483
#, python-format
msgid "Not a buffer object: %r"
msgstr ""

#: ../lib/pytis/data/types_.py:2624
#, python-format
msgid "Maximal pixel size %(maxsize)s exceeded"
msgstr ""

#: ../lib/pytis/data/types_.py:2626
#, python-format
msgid "Minimal pixel size %(minsize)s exceeded"
msgstr ""

#: ../lib/pytis/data/types_.py:2628
#, python-format
msgid "Unsupported format %(format)s; valid formats: %(formats)s"
msgstr ""

#: ../lib/pytis/data/types_.py:2644
msgid "Invalid graphics format"
msgstr ""

#: ../lib/pytis/data/types_.py:2753
msgid "Invalid hierarchical value format"
msgstr ""

#: ../lib/pytis/data/types_.py:2755
msgid "One of hierarchical value items is too long"
msgstr ""

#: ../lib/pytis/data/types_.py:2757
msgid "One of hierarchical value items contains invalid characters"
msgstr ""

#: ../lib/pytis/presentation/field.py:479
msgid "Such value already exists."
msgstr ""

#: ../lib/pytis/presentation/field.py:722
msgid "unlimited"
msgstr ""

#, fuzzy
#~ msgid "Instructions"
#~ msgstr "Műveletek"

#, fuzzy
#~ msgid "Selections"
#~ msgstr "Műveletek"

#, fuzzy
#~ msgid "Dictation"
#~ msgstr "Műveletek"
