# Pytis translations 
# Copyright (C) 2008-2011 Brailcom, o.p.s. 
# This file is distributed under the same license as the Pytis package. 
#
msgid ""
msgstr ""
"Project-Id-Version: 0.1\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2013-07-24 17:08+0200\n"
"PO-Revision-Date: 2011-12-29 14:56+0100\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: Hungarian <wiking@lists.freebsoft.org>\n"
"Language: hu\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: ../lib/pytis/data/access.py:434
msgid "Access denied"
msgstr ""

#: ../lib/pytis/data/dbapi.py:73
msgid "Can't connect to database"
msgstr ""

#: ../lib/pytis/data/dbapi.py:151
msgid "Database interface error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:167 ../lib/pytis/data/dbapi.py:261
msgid "Database connection error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:181 ../lib/pytis/data/pgsql.py:87
#: ../lib/pytis/data/pgsql.py:94
msgid "Database operational error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:185 ../lib/pytis/data/pgsql.py:99
msgid "Database integrity violation"
msgstr ""

#: ../lib/pytis/data/dbdata.py:300
msgid "Too many database connections"
msgstr ""

#: ../lib/pytis/data/dbdata.py:696
msgid "Database error"
msgstr ""

#: ../lib/pytis/data/dbdata.py:764
msgid "Invalid user name or password"
msgstr ""

#: ../lib/pytis/data/pgsql.py:60
msgid "Unable to connect to the database"
msgstr ""

#: ../lib/pytis/data/pgsql.py:69
msgid "Query arguments unsupported by the pgsql backend"
msgstr ""

#: ../lib/pytis/data/postgresql.py:239 ../lib/pytis/data/postgresql.py:325
#: ../lib/pytis/data/postgresql.py:337
msgid "Method not implemented"
msgstr ""

#: ../lib/pytis/data/postgresql.py:447
msgid "Characters present in data not representable in database encoding"
msgstr ""

#: ../lib/pytis/data/postgresql.py:3581
msgid "Invalid database counter value"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:162
msgid "Empty value"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:164
msgid "Invalid value"
msgstr ""

#: ../lib/pytis/data/types_.py:396
#, python-format
msgid "Wildcard matching not supported for values of type '%s'."
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:530
#, python-format
msgid "Minimal value is %(minimum)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:533
#, python-format
msgid "Maximal value is %(maximum)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:610
#, python-format
msgid "Minimal size %(minlen)s not satisfied"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:613
#, python-format
msgid "Maximal length %(maxlen)s characters exceeded"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:715
msgid "Not an integer"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:825
msgid "Invalid number"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:959
#, python-format
msgid "Minimal length %(minlen)s characters not satisfied"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:961 ../lib/pytis/data/types_.py:2008
#, python-format
msgid "Maximal size %(maxlen)s exceeded"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1049
msgid "Enter the password twice to eliminate typos"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1052
msgid "Passwords don't match"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1055
msgid "Invalid MD5 hash"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1058
msgid "Please use mix of letters and non-letters in your password"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1120 ../lib/pytis/data/types_.py:1154
#: ../lib/pytis/data/types_.py:1190 ../lib/pytis/data/types_.py:1819
msgid "Invalid format"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1140
msgid "Invalid color format ('#RGB' or '#RRGGBB')"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1156
#, python-format
msgid "Invalid inet address mask: %(mask)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1158
#, python-format
msgid "Invalid inet address value %(addr)s"
msgstr ""

#: ../lib/pytis/data/types_.py:1316
msgid "Invalid date or time format"
msgstr ""

#: ../lib/pytis/data/types_.py:1317
msgid "Invalid date or time"
msgstr ""

#: ../lib/pytis/data/types_.py:1318
msgid "Date outside the allowed range"
msgstr ""

#: ../lib/pytis/data/types_.py:1973
msgid "Invalid boolean type input value"
msgstr ""

#: ../lib/pytis/data/types_.py:2054
#, python-format
msgid "Not a buffer object: %r"
msgstr ""

#: ../lib/pytis/data/types_.py:2190
#, python-format
msgid "Maximal pixel size %(maxsize)s exceeded"
msgstr ""

#: ../lib/pytis/data/types_.py:2192
#, python-format
msgid "Minimal pixel size %(minsize)s exceeded"
msgstr ""

#: ../lib/pytis/data/types_.py:2194
#, python-format
msgid "Unsupported format %(format)s; valid formats: %(formats)s"
msgstr ""

#: ../lib/pytis/data/types_.py:2210
msgid "Invalid graphics format"
msgstr ""

#: ../lib/pytis/data/types_.py:2315
msgid "Invalid hierarchical value format"
msgstr ""

#: ../lib/pytis/data/types_.py:2317
msgid "One of hierarchical value items is too long"
msgstr ""

#: ../lib/pytis/data/types_.py:2319
msgid "One of hierarchical value items contains invalid characters"
msgstr ""

#, fuzzy
#~ msgid "Instructions"
#~ msgstr "Műveletek"

#, fuzzy
#~ msgid "Selections"
#~ msgstr "Műveletek"

#, fuzzy
#~ msgid "Dictation"
#~ msgstr "Műveletek"
