# Pytis translations
# Copyright (C) 2006-2011 OUI Technology Ltd.
# This file is distributed under the same license as the Pytis package.
# Paweł Loba <ploba@rogers.com>, 2006
#
msgid ""
msgstr ""
"Project-Id-Version: 0.1\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2022-09-07 11:50+0200\n"
"PO-Revision-Date: 2011-12-29 14:58+0100\n"
"Last-Translator: Pawel Loba <ploba@rogers.com>\n"
"Language-Team: Polish <wiking@lists.freebsoft.org>\n"
"Language: pl\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 "
"|| n%100>=20) ? 1 : 2;\n"

#: ../lib/pytis/data/access.py:432
msgid "Access denied"
msgstr ""

#: ../lib/pytis/data/dbapi.py:89
msgid "Waiting for server recovery"
msgstr ""

#: ../lib/pytis/data/dbapi.py:101
msgid "Can't connect to database"
msgstr ""

#: ../lib/pytis/data/dbapi.py:231
msgid "Database interface error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:250
msgid "Database connection timeout"
msgstr ""

#: ../lib/pytis/data/dbapi.py:252 ../lib/pytis/data/dbapi.py:387
msgid "Database connection error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:266
msgid "Database operational error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:274
msgid "Database internal error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:278
msgid "Database integrity violation"
msgstr ""

#: ../lib/pytis/data/dbdata.py:292
msgid "Too many database connections"
msgstr ""

#: ../lib/pytis/data/dbdata.py:722
msgid "Database error"
msgstr ""

#: ../lib/pytis/data/dbdata.py:791
#, fuzzy
msgid "Invalid user name or password"
msgstr "Niewłaściwy format daty lub czasu"

#: ../lib/pytis/data/postgresql.py:426 ../lib/pytis/data/postgresql.py:536
#: ../lib/pytis/data/postgresql.py:548
msgid "Method not implemented"
msgstr ""

#: ../lib/pytis/data/postgresql.py:3556
#, fuzzy
msgid "Invalid database counter value"
msgstr "Niewłaściwy format daty lub czasu"

#: ../lib/pytis/data/types_.py:373
#, python-format
msgid "Wildcard matching not supported for values of type '%s'."
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:380
msgid "Empty value"
msgstr "Pusta wartość"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:396
#, fuzzy
msgid "Invalid value"
msgstr "Niepoprawny numer"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:544
#, python-format
msgid "Minimal value is %(minimum)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:547
#, python-format
msgid "Maximal value is %(maximum)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:587
#, fuzzy, python-format
msgid "Minimal size %(minlen)s not satisfied"
msgstr "Ciąg przekracza maksymalną długość %(maxlen)d"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:589
#, fuzzy, python-format
msgid "Maximal size %(maxlen)s exceeded"
msgstr "Ciąg przekracza maksymalną długość %(maxlen)d"

#: ../lib/pytis/data/types_.py:740
msgid "Lower range bound higher than the upper one"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:833
msgid "Not an integer"
msgstr "To nie jest liczba całkowita"

#: ../lib/pytis/data/types_.py:1005
msgid "Invalid number"
msgstr "Niepoprawny numer"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1138
#, fuzzy, python-format
msgid "Minimal length %(minlen)s characters not satisfied"
msgstr "Ciąg przekracza maksymalną długość %(maxlen)d"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1140
#, fuzzy, python-format
msgid "Maximal length %(maxlen)s characters exceeded"
msgstr "Ciąg przekracza maksymalną długość %(maxlen)d"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1266
msgid "Please use mix of letters and non-letters in your password"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1272
msgid "Enter the password twice to eliminate typos"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1275
msgid "Passwords don't match"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1298
#, fuzzy
msgid "Invalid MD5 hash"
msgstr "Niepoprawna wartość"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1305 ../lib/pytis/data/types_.py:1343
#: ../lib/pytis/data/types_.py:1373 ../lib/pytis/data/types_.py:1393
#: ../lib/pytis/data/types_.py:2113
msgid "Invalid format"
msgstr "Niewłaściwy format"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1328
msgid "Invalid color format ('#RGB' or '#RRGGBB')"
msgstr "Niewłaściwy format koloru ('#RGB' lub '#RRGGBB')"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1348
#, python-format
msgid "Invalid inet address mask: %(mask)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1355
#, python-format
msgid "Invalid inet address value %(addr)s"
msgstr ""

#: ../lib/pytis/data/types_.py:1520
msgid "Invalid date or time format"
msgstr "Niewłaściwy format daty lub czasu"

#: ../lib/pytis/data/types_.py:1727
msgid "Date outside the allowed range"
msgstr "Data poza dopuszczalnym obrębem"

#: ../lib/pytis/data/types_.py:2129
#, python-format
msgid "%d min"
msgid_plural "%d min"
msgstr[0] ""
msgstr[1] ""
msgstr[2] ""

#: ../lib/pytis/data/types_.py:2131
#, python-format
msgid "%d h"
msgid_plural "%d h"
msgstr[0] ""
msgstr[1] ""
msgstr[2] ""

#: ../lib/pytis/data/types_.py:2133
#, python-format
msgid "%d day"
msgid_plural "%d days"
msgstr[0] ""
msgstr[1] ""
msgstr[2] ""

#: ../lib/pytis/data/types_.py:2135
msgid "less than 1 min"
msgstr ""

#: ../lib/pytis/data/types_.py:2246
#, fuzzy
msgid "Invalid boolean type input value"
msgstr "Niewłaściwy format daty lub czasu"

#: ../lib/pytis/data/types_.py:2473
#, fuzzy
msgid "Invalid graphics format"
msgstr "Niewłaściwy format"

#: ../lib/pytis/data/types_.py:2531
#, fuzzy, python-format
msgid "Minimal pixel size %(minsize)s exceeded"
msgstr "Ciąg przekracza maksymalną długość %(maxlen)d"

#: ../lib/pytis/data/types_.py:2534
#, fuzzy, python-format
msgid "Maximal pixel size %(maxsize)s exceeded"
msgstr "Ciąg przekracza maksymalną długość %(maxlen)d"

#: ../lib/pytis/data/types_.py:2538
#, python-format
msgid "Unsupported format %(format)s; valid formats: %(formats)s"
msgstr ""

#: ../lib/pytis/data/types_.py:2585
#, fuzzy
msgid "Invalid hierarchical value format"
msgstr "Niewłaściwy format daty lub czasu"

#: ../lib/pytis/data/types_.py:2587
#, fuzzy
msgid "One of hierarchical value items is too long"
msgstr "Niewłaściwy format daty lub czasu"

#: ../lib/pytis/data/types_.py:2589
msgid "One of hierarchical value items contains invalid characters"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:2754
msgid "Not a JSON string"
msgstr ""

#: ../lib/pytis/data/types_.py:2756
msgid "Unsupported JSON value"
msgstr ""

#: ../lib/pytis/data/types_.py:2762
msgid "JSON value doesn't match schema definition"
msgstr ""

#: ../lib/pytis/presentation/field.py:482
msgid "Such value already exists."
msgstr ""

#: ../lib/pytis/presentation/field.py:745
msgid "unlimited"
msgstr ""

#~ msgid "Invalid date or time"
#~ msgstr "Niewłaściwy format daty lub czasu"

#, fuzzy
#~ msgid "String exceeds max length %(maxlen)s characters"
#~ msgstr "Ciąg przekracza maksymalną długość %(maxlen)d"

#~ msgid "Submit"
#~ msgstr "Wyślij"

#~ msgid "Yes"
#~ msgstr "Tak"

#~ msgid "No"
#~ msgstr "Nie"

#~ msgid "Reset"
#~ msgstr "Odśwież"

#, fuzzy
#~ msgid "Sum"
#~ msgstr "Wyślij"

#~ msgid "No records."
#~ msgstr "Nie ma wpisu."

#, fuzzy
#~ msgid "Total records:"
#~ msgstr "Nie ma wpisu."

#, fuzzy
#~ msgid "Instructions"
#~ msgstr "Działania"

#, fuzzy
#~ msgid "Selections"
#~ msgstr "Działania"

#, fuzzy
#~ msgid "Dictation"
#~ msgstr "Działania"

#~ msgid "reduced"
#~ msgstr "zredukowany"
