# Pytis translations 
# Copyright (C) 2008-2011 Brailcom, o.p.s. 
# This file is distributed under the same license as the Pytis package. 
#
msgid ""
msgstr ""
"Project-Id-Version: 0.1\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-05-28 10:15+0200\n"
"PO-Revision-Date: 2011-12-29 14:56+0100\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: Hungarian <wiking@lists.freebsoft.org>\n"
"Language: hu\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: ../lib/pytis/data/access.py:434
msgid "Access denied"
msgstr ""

#: ../lib/pytis/data/dbapi.py:83
msgid "Can't connect to database"
msgstr ""

#: ../lib/pytis/data/dbapi.py:171
msgid "Database interface error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:187
msgid "Database connection timeout"
msgstr ""

#: ../lib/pytis/data/dbapi.py:189 ../lib/pytis/data/dbapi.py:299
msgid "Database connection error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:203 ../lib/pytis/data/pgsql.py:87
#: ../lib/pytis/data/pgsql.py:94
msgid "Database operational error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:207 ../lib/pytis/data/pgsql.py:99
msgid "Database integrity violation"
msgstr ""

#: ../lib/pytis/data/dbdata.py:299
msgid "Too many database connections"
msgstr ""

#: ../lib/pytis/data/dbdata.py:707
msgid "Database error"
msgstr ""

#: ../lib/pytis/data/dbdata.py:775
msgid "Invalid user name or password"
msgstr ""

#: ../lib/pytis/data/pgsql.py:60
msgid "Unable to connect to the database"
msgstr ""

#: ../lib/pytis/data/pgsql.py:69
msgid "Query arguments unsupported by the pgsql backend"
msgstr ""

#: ../lib/pytis/data/postgresql.py:275 ../lib/pytis/data/postgresql.py:361
#: ../lib/pytis/data/postgresql.py:373
msgid "Method not implemented"
msgstr ""

#: ../lib/pytis/data/postgresql.py:508
msgid "Characters present in data not representable in database encoding"
msgstr ""

#: ../lib/pytis/data/postgresql.py:3690
msgid "Invalid database counter value"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:162
msgid "Empty value"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:164
msgid "Invalid value"
msgstr ""

#: ../lib/pytis/data/types_.py:396
#, python-format
msgid "Wildcard matching not supported for values of type '%s'."
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:530
#, python-format
msgid "Minimal value is %(minimum)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:533
#, python-format
msgid "Maximal value is %(maximum)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:610
#, python-format
msgid "Minimal size %(minlen)s not satisfied"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:613
#, python-format
msgid "Maximal length %(maxlen)s characters exceeded"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:715
msgid "Not an integer"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:825
msgid "Invalid number"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:959
#, python-format
msgid "Minimal length %(minlen)s characters not satisfied"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:961 ../lib/pytis/data/types_.py:2012
#, python-format
msgid "Maximal size %(maxlen)s exceeded"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1051
msgid "Enter the password twice to eliminate typos"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1054
msgid "Passwords don't match"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1057
msgid "Invalid MD5 hash"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1060
msgid "Please use mix of letters and non-letters in your password"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1122 ../lib/pytis/data/types_.py:1158
#: ../lib/pytis/data/types_.py:1194 ../lib/pytis/data/types_.py:1823
msgid "Invalid format"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1144
msgid "Invalid color format ('#RGB' or '#RRGGBB')"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1160
#, python-format
msgid "Invalid inet address mask: %(mask)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1162
#, python-format
msgid "Invalid inet address value %(addr)s"
msgstr ""

#: ../lib/pytis/data/types_.py:1320
msgid "Invalid date or time format"
msgstr ""

#: ../lib/pytis/data/types_.py:1321
msgid "Invalid date or time"
msgstr ""

#: ../lib/pytis/data/types_.py:1322
msgid "Date outside the allowed range"
msgstr ""

#: ../lib/pytis/data/types_.py:1977
msgid "Invalid boolean type input value"
msgstr ""

#: ../lib/pytis/data/types_.py:2058
#, python-format
msgid "Not a buffer object: %r"
msgstr ""

#: ../lib/pytis/data/types_.py:2194
#, python-format
msgid "Maximal pixel size %(maxsize)s exceeded"
msgstr ""

#: ../lib/pytis/data/types_.py:2196
#, python-format
msgid "Minimal pixel size %(minsize)s exceeded"
msgstr ""

#: ../lib/pytis/data/types_.py:2198
#, python-format
msgid "Unsupported format %(format)s; valid formats: %(formats)s"
msgstr ""

#: ../lib/pytis/data/types_.py:2214
msgid "Invalid graphics format"
msgstr ""

#: ../lib/pytis/data/types_.py:2319
msgid "Invalid hierarchical value format"
msgstr ""

#: ../lib/pytis/data/types_.py:2321
msgid "One of hierarchical value items is too long"
msgstr ""

#: ../lib/pytis/data/types_.py:2323
msgid "One of hierarchical value items contains invalid characters"
msgstr ""

#, fuzzy
#~ msgid "Instructions"
#~ msgstr "Műveletek"

#, fuzzy
#~ msgid "Selections"
#~ msgstr "Műveletek"

#, fuzzy
#~ msgid "Dictation"
#~ msgstr "Műveletek"
