# Pytis translations
# Copyright (C) 2006-2017 OUI Technology Ltd.
# This file is distributed under the same license as the Pytis package.
# Tomas Cerha <cerha@brailcom.org>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: pytis 0.1\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2025-06-10 21:37+0200\n"
"PO-Revision-Date: 2022-05-13 14:08+0200\n"
"Last-Translator: Hynek Hanke <hanke@brailcom.org>\n"
"Language-Team: Czech <wiking@lists.freebsoft.org>\n"
"Language: cs\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=((n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2);\n"

#: ../lib/pytis/data/access.py:433
msgid "Access denied"
msgstr "Neoprávněný přístup"

#: ../lib/pytis/data/dbapi.py:91
msgid "Waiting for server recovery"
msgstr "Čekám na zotavení serveru"

#: ../lib/pytis/data/dbapi.py:103
msgid "Can't connect to database"
msgstr "Nemohu se připojit do databáze"

#: ../lib/pytis/data/dbapi.py:233
msgid "Database interface error"
msgstr "Chyba v databázovém rozhraní"

#: ../lib/pytis/data/dbapi.py:252
msgid "Database connection timeout"
msgstr "Vypršel časový limit pro navázání databázového spojení"

#: ../lib/pytis/data/dbapi.py:254 ../lib/pytis/data/dbapi.py:389
msgid "Database connection error"
msgstr "Chyba databázového spojení"

#: ../lib/pytis/data/dbapi.py:268
msgid "Database operational error"
msgstr "Chyba databázové operace"

#: ../lib/pytis/data/dbapi.py:276
msgid "Database internal error"
msgstr "Interní databázová chyba"

#: ../lib/pytis/data/dbapi.py:280
msgid "Database integrity violation"
msgstr "Porušení integrity dat v databázi"

#: ../lib/pytis/data/dbdata.py:294
msgid "Too many database connections"
msgstr "Příliš mnoho databázových spojení"

#: ../lib/pytis/data/dbdata.py:723
msgid "Database error"
msgstr "Databázová chyba"

#: ../lib/pytis/data/dbdata.py:791
msgid "Invalid user name or password"
msgstr "Chybné uživatelské jméno nebo heslo"

#: ../lib/pytis/data/postgresql.py:443 ../lib/pytis/data/postgresql.py:553
#: ../lib/pytis/data/postgresql.py:565
msgid "Method not implemented"
msgstr "Volána neimplementovaná metoda"

#: ../lib/pytis/data/postgresql.py:3583
msgid "Invalid database counter value"
msgstr "Chybná hodnota čítače z databáze"

#: ../lib/pytis/data/types_.py:374
#, python-format
msgid "Wildcard matching not supported for values of type '%s'."
msgstr "Hvězdičkové výrazy nejsou podporovány pro hodnoty typu '%s'."

#. User input validation error message.
#: ../lib/pytis/data/types_.py:381
msgid "Empty value"
msgstr "Prázdná hodnota"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:397
msgid "Invalid value"
msgstr "Neplatná hodnota"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:545
#, python-format
msgid "Minimal value is %(minimum)s"
msgstr "Minimální hodnota je %(minimum)s"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:548
#, python-format
msgid "Maximal value is %(maximum)s"
msgstr "Maximální hodnota je %(maximum)s"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:588
#, python-format
msgid "Minimal size %(minlen)s not satisfied"
msgstr "Nedodržena minimální velikost %(minlen)s"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:590
#, python-format
msgid "Maximal size %(maxlen)s exceeded"
msgstr "Maximální velikost %(maxlen)s překročena"

#: ../lib/pytis/data/types_.py:741
msgid "Lower range bound higher than the upper one"
msgstr "Dolní hranice rozsahu je vyšší než horní"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:834
msgid "Not an integer"
msgstr "Není to celé číslo"

#: ../lib/pytis/data/types_.py:1009
msgid "Invalid number"
msgstr "Není to povolené číslo"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1145
#, python-format
msgid "Minimal length %(minlen)s characters not satisfied"
msgstr "Nedodržena minimální délka %(minlen)s znaků"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1147
#, python-format
msgid "Maximal length %(maxlen)s characters exceeded"
msgstr "Řetězec přesahuje maximální délku %(maxlen)s znaků"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1288
msgid "Please use mix of letters and non-letters in your password"
msgstr "Použijte ve svém hesle kombinaci písmenných a nepísmenných znaků"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1294
msgid "Enter the password twice to eliminate typos"
msgstr "Zadejte heslo dvakrát pro eliminování překlepů"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1297
msgid "Passwords don't match"
msgstr "Kontrolní zadání hesla neodpovídá"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1320
msgid "Invalid MD5 hash"
msgstr "Neplatná MD5 suma"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1327 ../lib/pytis/data/types_.py:1365
#: ../lib/pytis/data/types_.py:1395 ../lib/pytis/data/types_.py:1415
#: ../lib/pytis/data/types_.py:2145
msgid "Invalid format"
msgstr "Neplatný formát"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1350
msgid "Invalid color format ('#RGB' or '#RRGGBB')"
msgstr "Formát barvy neodpovídá ('#RGB' nebo '#RRGGBB')"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1370
#, python-format
msgid "Invalid inet address mask: %(mask)s"
msgstr "Neplatná maska inet adresy: %(mask)s"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1377
#, python-format
msgid "Invalid inet address value %(addr)s"
msgstr "Neplatná hodnota inet adresy: %(addr)s"

#: ../lib/pytis/data/types_.py:1544
msgid "Invalid date or time format"
msgstr "Chybný formát data nebo času"

#: ../lib/pytis/data/types_.py:1757
msgid "Date outside the allowed range"
msgstr "Datum mimo povolený rozsah"

#: ../lib/pytis/data/types_.py:2161
#, python-format
msgid "%d min"
msgid_plural "%d min"
msgstr[0] "%d min"
msgstr[1] "%d min"
msgstr[2] "%d min"

#: ../lib/pytis/data/types_.py:2163
#, python-format
msgid "%d h"
msgid_plural "%d h"
msgstr[0] "%d hod"
msgstr[1] "%d hod"
msgstr[2] "%d hod"

#: ../lib/pytis/data/types_.py:2165
#, python-format
msgid "%d day"
msgid_plural "%d days"
msgstr[0] "%d den"
msgstr[1] "%d dny"
msgstr[2] "%d dní"

#: ../lib/pytis/data/types_.py:2167
msgid "less than 1 min"
msgstr "méně než 1 min"

#: ../lib/pytis/data/types_.py:2278
msgid "Invalid boolean type input value"
msgstr "Neplatná vstupní hodnota typu boolean"

#: ../lib/pytis/data/types_.py:2505
msgid "Invalid graphics format"
msgstr "Neplatný grafický formát"

#: ../lib/pytis/data/types_.py:2563
#, python-format
msgid "Minimal pixel size %(minsize)s exceeded"
msgstr "Minimální rozměr %(minsize)s pixelů nedodržen"

#: ../lib/pytis/data/types_.py:2566
#, python-format
msgid "Maximal pixel size %(maxsize)s exceeded"
msgstr "Maximální rozměr %(maxsize)s pixelů překročen"

#: ../lib/pytis/data/types_.py:2570
#, python-format
msgid "Unsupported format %(format)s; valid formats: %(formats)s"
msgstr "Nepodporovaný formát %(format)s; platné formáty: %(formats)s"

#: ../lib/pytis/data/types_.py:2617
msgid "Invalid hierarchical value format"
msgstr "Chybný formát hierarchické hodnoty"

#: ../lib/pytis/data/types_.py:2619
msgid "One of hierarchical value items is too long"
msgstr "Jedna z položek hierarchické hodnoty je příliš dlouhá"

#: ../lib/pytis/data/types_.py:2621
msgid "One of hierarchical value items contains invalid characters"
msgstr "Jedna z položek hierarchické hodnoty obsahuje neplatné znaky"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:2802
msgid "Not a JSON string"
msgstr "Není JSON řetězec"

#: ../lib/pytis/data/types_.py:2806
msgid "Unsupported JSON value"
msgstr "Nepodporovaná JSON hodnota"

#: ../lib/pytis/data/types_.py:2812
msgid "JSON value doesn't match schema definition"
msgstr "JSON hodnota neodpovídá definici schematu"

#: ../lib/pytis/presentation/field.py:484
msgid "Such value already exists."
msgstr "Taková hodnota již existuje"

#: ../lib/pytis/presentation/field.py:759
msgid "unlimited"
msgstr "neomezeno"

#: ../lib/pytis/presentation/spec.py:5802
#, python-format
msgid ""
"You don't have priviledges to invoke the action '%s'.\n"
"Please contact the access rights administrator."
msgstr ""
"Nemáte oprávnění pro vyvolání akce '%s'.\n"
"Kontaktujte prosím správce přístupových práv."

#~ msgid "Invalid date or time"
#~ msgstr "Chybné datum nebo čas"

#, python-format
#~ msgid "Not a buffer object: %r"
#~ msgstr "Není to objekt typu buffer: %r"

#~ msgid "Application error. You can report it to get it fixed soon."
#~ msgstr ""
#~ "Chyba aplikace. Můžete ji nyní nahlásit, aby mohla být co nejdříve "
#~ "opravena."

#~ msgid "Unable to connect to the database"
#~ msgstr "Nelze se připojit k databázi"

#~ msgid "Query arguments unsupported by the pgsql backend"
#~ msgstr "Argumenty dotazu nejsou podporovány při použití pgsql backendu"

#~ msgid "Characters present in data not representable in database encoding"
#~ msgstr "Data obsahují znaky, které nelze reprezentovat v kódování databáze"

#~ msgid "String exceeds max length %(maxlen)s characters"
#~ msgstr "Řetězec přesahuje maximální délku %(maxlen)s znaků"

#~ msgid "Minimal length %(minlen)s not satisfied"
#~ msgstr "Nedodržena minimální délka %(minlen)s"
